### Создание клиента
POST http://127.0.0.1:8080/api/v1/clients
accept: */*
Content-Type: application/json

{
  "email": "email2@email.com",
  "phoneNumber": "+7-913-937-5656",
  "status": "ACTIVE",
  "properties": {
    "firstName": "Иван",
    "lastName": "Иванов"
  }
}

### Получение клиента
GET http://127.0.0.1:8080/api/v1/clients/17
accept: */*

### Изменение клиента
PUT http://127.0.0.1:8080/api/v1/clients/17
accept: */*
Content-Type: application/json

{
  "email": "email2@email.com",
  "phoneNumber": "+7-913-937-5656",
  "status": "ACTIVE",
  "properties": {
    "first_Name": "Иван2",
    "last_Name": "Иванов2"
  }
}

